[package]
name    = "bdf"
version = "0.7.0"
edition = "2021"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "BDF format handling."
repository  = "https://github.com/meh/rust-bdf"
keywords    = ["font", "bdf"]

[features]
default = []

[dependencies]
bit-set = "0.5.2"
